export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const UPDATE_CARD_DATA = 'UPDATE_CARD_DATA';
export const CHANGE_IP = 'CHANGE_IP';
export const UPDATE_USERLIST = 'UPDATE_USERLIST';
export const UPDATE_OWNERSHIP_DATA = 'UPDATE_OWNERSHIP_DATA';
export const DEBUG_MENU_VISIBLE = 'DEBUG_MENU_VISIBLE';

//requests

export const FETCH_USER_REQUEST = 'FETCH_USER_DATA';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';
