export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const UPDATE_CARD_DATA = 'UPDATE_CARD_DATA';
export const CHANGE_IP = 'CHANGE_IP';
export const UPDATE_USERLIST = 'UPDATE_USERLIST';
export const UPDATE_OWNERSHIP_DATA = 'UPDATE_OWNERSHIP_DATA';